version: '3.8'

services:
  # 1. PostgreSQL Database (ACID Store cho Orders và Outbox Table)
  postgres:
    image: postgres:16-alpine
    container_name: postgres_outbox
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical" # Cần thiết cho CDC (Debezium / Logical Replication)

  # 2. Redpanda (Apache Kafka Compatible Broker - Cực nhẹ, không cần Zookeeper)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    container_name: redpanda_broker
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"

  # 3. Redpanda Console (Web UI trực quan xem Kafka Topics, Partitions, Consumer Groups)
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.4.5
    container_name: redpanda_console
    environment:
      KAFKA_BROKERS: redpanda:9092
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

volumes:
  pgdata:
