version: '3.8'

services:
  # 1. API Load Balancer (Tầng 1 & 2)
  nginx:
    image: nginx:alpine
    container_name: capstone_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-1
      - app-2

  # 2. App Cluster (Tầng 3: Stateless Application Nodes)
  app-1:
    build: .
    container_name: capstone_app_1
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - DB_URL=postgres://postgres:password123@postgres:5432/flashsale
    depends_on:
      - redis
      - postgres

  app-2:
    build: .
    container_name: capstone_app_2
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - DB_URL=postgres://postgres:password123@postgres:5432/flashsale
    depends_on:
      - redis
      - postgres

  # 3. Redis In-Memory Engine (Tầng 3: Atomic Pre-deduction)
  redis:
    image: redis:7-alpine
    container_name: capstone_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]

  # 4. Message Queue (Tầng 4: Peak Shaving Buffer)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: capstone_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # 5. PostgreSQL Database (Tầng 5: Persistent Storage & Outbox)
  postgres:
    image: postgres:16-alpine
    container_name: capstone_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: flashsale
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
