events {
    worker_connections 1024;
}

http {
    upstream backend_cluster {
        server app-1:3000 max_fails=2 fail_timeout=5s;
        server app-2:3000 max_fails=2 fail_timeout=5s;
    }

    server {
        listen 80;
        server_name localhost;

        location /nginx-health {
            return 200 '{"status":"UP","gateway":"nginx"}\n';
            add_header Content-Type application/json;
        }

        location / {
            proxy_pass http://backend_cluster;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;
            proxy_send_timeout 5s;

            proxy_next_upstream error timeout invalid_header http_502 http_503;
            proxy_next_upstream_tries 3;
            proxy_next_upstream_timeout 5s;

            add_header X-Upstream-Addr $upstream_addr always;
            add_header X-Upstream-Response-Time $upstream_response_time always;
        }
    }
}
